<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="29" passed="15" failed="14" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-18T00:55:09 IST" name="Suite" finished-at="2023-09-18T01:12:57 IST" duration-ms="1068132">
    <groups>
    </groups>
    <test started-at="2023-09-18T00:55:09 IST" name="HrmTest1" finished-at="2023-09-18T01:12:33 IST" duration-ms="1043730">
      <class name="com.hrm.testcases.TC_005_VerifyLogoutModule">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_005_VerifyLogoutModule@51f49060]" started-at="2023-09-18T01:10:58 IST" name="setup" finished-at="2023-09-18T01:11:16 IST" duration-ms="17740" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyContentsOfTheUserProfileBtn()[pri:0, instance:com.hrm.testcases.TC_005_VerifyLogoutModule@51f49060]" started-at="2023-09-18T01:11:16 IST" name="verifyContentsOfTheUserProfileBtn" finished-at="2023-09-18T01:11:26 IST" duration-ms="9566" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyContentsOfTheUserProfileBtn -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_005_VerifyLogoutModule@51f49060]" started-at="2023-09-18T01:11:26 IST" name="tearDown" finished-at="2023-09-18T01:11:29 IST" duration-ms="2875" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_005_VerifyLogoutModule@51f49060]" started-at="2023-09-18T01:11:29 IST" name="setup" finished-at="2023-09-18T01:11:45 IST" duration-ms="16598" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLogout()[pri:0, instance:com.hrm.testcases.TC_005_VerifyLogoutModule@51f49060]" started-at="2023-09-18T01:11:45 IST" name="verifyLogout" finished-at="2023-09-18T01:11:57 IST" duration-ms="12293" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogout -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_005_VerifyLogoutModule@51f49060]" started-at="2023-09-18T01:11:57 IST" name="tearDown" finished-at="2023-09-18T01:12:01 IST" duration-ms="3042" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.hrm.testcases.TC_005_VerifyLogoutModule -->
      <class name="com.hrm.testcases.TC_004_FieldLevelValidations">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_004_FieldLevelValidations@3b366632]" started-at="2023-09-18T01:06:43 IST" name="setup" finished-at="2023-09-18T01:07:03 IST" duration-ms="19502" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validatingAddUserWhenEmployeeNameFieldIsEmpty()[pri:0, instance:com.hrm.testcases.TC_004_FieldLevelValidations@3b366632]" started-at="2023-09-18T01:07:03 IST" name="validatingAddUserWhenEmployeeNameFieldIsEmpty" finished-at="2023-09-18T01:07:27 IST" duration-ms="24266" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.hrm.testcases.TC_004_FieldLevelValidations.validatingAddUserWhenEmployeeNameFieldIsEmpty(TC_004_FieldLevelValidations.java:103)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatingAddUserWhenEmployeeNameFieldIsEmpty -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_004_FieldLevelValidations@3b366632]" started-at="2023-09-18T01:07:27 IST" name="tearDown" finished-at="2023-09-18T01:07:30 IST" duration-ms="2575" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_004_FieldLevelValidations@3b366632]" started-at="2023-09-18T01:07:30 IST" name="setup" finished-at="2023-09-18T01:07:48 IST" duration-ms="18874" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validatingAddUserWhenEmployeeNameFieldValuesAreLessThanMinimum()[pri:0, instance:com.hrm.testcases.TC_004_FieldLevelValidations@3b366632]" started-at="2023-09-18T01:07:48 IST" name="validatingAddUserWhenEmployeeNameFieldValuesAreLessThanMinimum" finished-at="2023-09-18T01:08:11 IST" duration-ms="22671" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.hrm.testcases.TC_004_FieldLevelValidations.validatingAddUserWhenEmployeeNameFieldValuesAreLessThanMinimum(TC_004_FieldLevelValidations.java:157)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatingAddUserWhenEmployeeNameFieldValuesAreLessThanMinimum -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_004_FieldLevelValidations@3b366632]" started-at="2023-09-18T01:08:11 IST" name="tearDown" finished-at="2023-09-18T01:08:13 IST" duration-ms="2002" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_004_FieldLevelValidations@3b366632]" started-at="2023-09-18T01:08:13 IST" name="setup" finished-at="2023-09-18T01:08:33 IST" duration-ms="19709" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validatingAddUserWhenUserameFieldIsEmpty()[pri:0, instance:com.hrm.testcases.TC_004_FieldLevelValidations@3b366632]" started-at="2023-09-18T01:08:33 IST" name="validatingAddUserWhenUserameFieldIsEmpty" finished-at="2023-09-18T01:08:53 IST" duration-ms="19829" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.hrm.testcases.TC_004_FieldLevelValidations.validatingAddUserWhenUserameFieldIsEmpty(TC_004_FieldLevelValidations.java:207)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatingAddUserWhenUserameFieldIsEmpty -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_004_FieldLevelValidations@3b366632]" started-at="2023-09-18T01:08:53 IST" name="tearDown" finished-at="2023-09-18T01:08:55 IST" duration-ms="2211" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_004_FieldLevelValidations@3b366632]" started-at="2023-09-18T01:08:55 IST" name="setup" finished-at="2023-09-18T01:09:14 IST" duration-ms="18850" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verfyAddUserUsernameFieldForOnlyAlphaNumeric()[pri:0, instance:com.hrm.testcases.TC_004_FieldLevelValidations@3b366632]" started-at="2023-09-18T01:09:14 IST" name="verfyAddUserUsernameFieldForOnlyAlphaNumeric" finished-at="2023-09-18T01:09:37 IST" duration-ms="23614" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.hrm.testcases.TC_004_FieldLevelValidations.verfyAddUserUsernameFieldForOnlyAlphaNumeric(TC_004_FieldLevelValidations.java:333)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfyAddUserUsernameFieldForOnlyAlphaNumeric -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_004_FieldLevelValidations@3b366632]" started-at="2023-09-18T01:09:37 IST" name="tearDown" finished-at="2023-09-18T01:09:43 IST" duration-ms="6008" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_004_FieldLevelValidations@3b366632]" started-at="2023-09-18T01:09:43 IST" name="setup" finished-at="2023-09-18T01:10:02 IST" duration-ms="18618" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyAddUserUsernameFieldValueLimit()[pri:0, instance:com.hrm.testcases.TC_004_FieldLevelValidations@3b366632]" started-at="2023-09-18T01:10:02 IST" name="verifyAddUserUsernameFieldValueLimit" finished-at="2023-09-18T01:10:27 IST" duration-ms="25320" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.hrm.testcases.TC_004_FieldLevelValidations.verifyAddUserUsernameFieldValueLimit(TC_004_FieldLevelValidations.java:281)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddUserUsernameFieldValueLimit -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_004_FieldLevelValidations@3b366632]" started-at="2023-09-18T01:10:27 IST" name="tearDown" finished-at="2023-09-18T01:10:30 IST" duration-ms="2183" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_004_FieldLevelValidations@3b366632]" started-at="2023-09-18T01:10:30 IST" name="setup" finished-at="2023-09-18T01:10:49 IST" duration-ms="19771" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginWithTwoWrongAttempts()[pri:0, instance:com.hrm.testcases.TC_004_FieldLevelValidations@3b366632]" started-at="2023-09-18T01:10:49 IST" name="verifyLoginWithTwoWrongAttempts" finished-at="2023-09-18T01:10:56 IST" duration-ms="6829" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.hrm.testcases.TC_004_FieldLevelValidations.verifyLoginWithTwoWrongAttempts(TC_004_FieldLevelValidations.java:52)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithTwoWrongAttempts -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_004_FieldLevelValidations@3b366632]" started-at="2023-09-18T01:10:56 IST" name="tearDown" finished-at="2023-09-18T01:10:58 IST" duration-ms="2280" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.hrm.testcases.TC_004_FieldLevelValidations -->
      <class name="com.hrm.testcases.TC_003_VerifyAdminModule">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T00:57:08 IST" name="setup" finished-at="2023-09-18T00:57:29 IST" duration-ms="21464" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="deleteUser()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T00:57:29 IST" name="deleteUser" finished-at="2023-09-18T00:58:01 IST" duration-ms="31948" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T00:58:01 IST" name="tearDown" finished-at="2023-09-18T00:58:04 IST" duration-ms="2441" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T00:58:04 IST" name="setup" finished-at="2023-09-18T00:58:21 IST" duration-ms="17468" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyAdminPageContents()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T00:58:21 IST" name="verifyAdminPageContents" finished-at="2023-09-18T00:58:30 IST" duration-ms="8816" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAdminPageContents -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T00:58:30 IST" name="tearDown" finished-at="2023-09-18T00:58:34 IST" duration-ms="4242" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T00:58:34 IST" name="setup" finished-at="2023-09-18T00:58:54 IST" duration-ms="19660" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyResultsForStatusEnabled()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T00:58:54 IST" name="verifyResultsForStatusEnabled" finished-at="2023-09-18T00:59:15 IST" duration-ms="20991" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyResultsForStatusEnabled -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T00:59:15 IST" name="tearDown" finished-at="2023-09-18T00:59:18 IST" duration-ms="3072" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T00:59:18 IST" name="setup" finished-at="2023-09-18T00:59:47 IST" duration-ms="28727" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyResultsForStatusDisabled()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T00:59:47 IST" name="verifyResultsForStatusDisabled" finished-at="2023-09-18T01:00:14 IST" duration-ms="27039" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyResultsForStatusDisabled -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:00:14 IST" name="tearDown" finished-at="2023-09-18T01:00:17 IST" duration-ms="3284" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:00:17 IST" name="setup" finished-at="2023-09-18T01:00:35 IST" duration-ms="18226" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyResultsForUserRoleESS()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:00:35 IST" name="verifyResultsForUserRoleESS" finished-at="2023-09-18T01:00:53 IST" duration-ms="18175" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyResultsForUserRoleESS -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:00:53 IST" name="tearDown" finished-at="2023-09-18T01:00:57 IST" duration-ms="3747" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:00:57 IST" name="setup" finished-at="2023-09-18T01:01:16 IST" duration-ms="18693" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyResultsForUserRoleAdmin()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:01:16 IST" name="verifyResultsForUserRoleAdmin" finished-at="2023-09-18T01:01:31 IST" duration-ms="15295" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyResultsForUserRoleAdmin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:01:31 IST" name="tearDown" finished-at="2023-09-18T01:01:34 IST" duration-ms="2708" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:01:34 IST" name="setup" finished-at="2023-09-18T01:01:56 IST" duration-ms="22468" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyUserRoleOptions()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:01:56 IST" name="verifyUserRoleOptions" finished-at="2023-09-18T01:02:04 IST" duration-ms="7946" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserRoleOptions -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:02:04 IST" name="tearDown" finished-at="2023-09-18T01:02:10 IST" duration-ms="5742" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:02:10 IST" name="setup" finished-at="2023-09-18T01:02:28 IST" duration-ms="18257" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyStatusAfterAddingNewUser()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:02:28 IST" name="verifyStatusAfterAddingNewUser" finished-at="2023-09-18T01:02:50 IST" duration-ms="21633" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyStatusAfterAddingNewUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:02:50 IST" name="tearDown" finished-at="2023-09-18T01:02:53 IST" duration-ms="3192" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:02:53 IST" name="setup" finished-at="2023-09-18T01:03:10 IST" duration-ms="17065" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifySearchResultWithExistingUsername()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:03:10 IST" name="verifySearchResultWithExistingUsername" finished-at="2023-09-18T01:03:21 IST" duration-ms="10798" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySearchResultWithExistingUsername -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:03:21 IST" name="tearDown" finished-at="2023-09-18T01:03:24 IST" duration-ms="2670" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:03:24 IST" name="setup" finished-at="2023-09-18T01:03:39 IST" duration-ms="15737" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyExistingEmployeeNameRecords()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:03:39 IST" name="verifyExistingEmployeeNameRecords" finished-at="2023-09-18T01:03:58 IST" duration-ms="18572" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistingEmployeeNameRecords -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:03:58 IST" name="tearDown" finished-at="2023-09-18T01:04:01 IST" duration-ms="2583" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:04:01 IST" name="setup" finished-at="2023-09-18T01:04:22 IST" duration-ms="21288" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyNonExistingEmployeeNameRecords()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:04:22 IST" name="verifyNonExistingEmployeeNameRecords" finished-at="2023-09-18T01:04:34 IST" duration-ms="11923" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.hrm.testcases.TC_003_VerifyAdminModule.verifyNonExistingEmployeeNameRecords(TC_003_VerifyAdminModule.java:299)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNonExistingEmployeeNameRecords -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:04:34 IST" name="tearDown" finished-at="2023-09-18T01:04:36 IST" duration-ms="1946" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:04:36 IST" name="setup" finished-at="2023-09-18T01:04:54 IST" duration-ms="17771" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyStatusContentsInDropDown()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:04:54 IST" name="verifyStatusContentsInDropDown" finished-at="2023-09-18T01:05:05 IST" duration-ms="11523" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyStatusContentsInDropDown -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:05:05 IST" name="tearDown" finished-at="2023-09-18T01:05:07 IST" duration-ms="2388" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:05:07 IST" name="setup" finished-at="2023-09-18T01:05:24 IST" duration-ms="16665" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="compareAddUserScreenshot()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:05:24 IST" name="compareAddUserScreenshot" finished-at="2023-09-18T01:05:41 IST" duration-ms="17248" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.hrm.testcases.TC_003_VerifyAdminModule.compareAddUserScreenshot(TC_003_VerifyAdminModule.java:471)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- compareAddUserScreenshot -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:05:41 IST" name="tearDown" finished-at="2023-09-18T01:05:43 IST" duration-ms="1943" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:05:43 IST" name="setup" finished-at="2023-09-18T01:06:04 IST" duration-ms="20803" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyByAddingNewDuplicateUsername()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:06:04 IST" name="verifyByAddingNewDuplicateUsername" finished-at="2023-09-18T01:06:41 IST" duration-ms="36608" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.hrm.testcases.TC_003_VerifyAdminModule.verifyByAddingNewDuplicateUsername(TC_003_VerifyAdminModule.java:594)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyByAddingNewDuplicateUsername -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_003_VerifyAdminModule@7fb9f71f]" started-at="2023-09-18T01:06:41 IST" name="tearDown" finished-at="2023-09-18T01:06:43 IST" duration-ms="2531" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.hrm.testcases.TC_003_VerifyAdminModule -->
      <class name="com.hrm.testcases.TC_001_VerifyHomePage">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_001_VerifyHomePage@3591009c]" started-at="2023-09-18T00:55:10 IST" name="setup" finished-at="2023-09-18T00:55:40 IST" duration-ms="30338" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="compareHomePageScreenshot()[pri:0, instance:com.hrm.testcases.TC_001_VerifyHomePage@3591009c]" started-at="2023-09-18T00:55:40 IST" name="compareHomePageScreenshot" finished-at="2023-09-18T00:55:55 IST" duration-ms="14768" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.hrm.testcases.TC_001_VerifyHomePage.compareHomePageScreenshot(TC_001_VerifyHomePage.java:39)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- compareHomePageScreenshot -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_001_VerifyHomePage@3591009c]" started-at="2023-09-18T00:55:55 IST" name="tearDown" finished-at="2023-09-18T00:56:01 IST" duration-ms="6548" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.hrm.testcases.TC_001_VerifyHomePage -->
      <class name="com.hrm.testcases.TC_007_VerifyDashboardModule">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_007_VerifyDashboardModule@514eedd8]" started-at="2023-09-18T01:12:01 IST" name="setup" finished-at="2023-09-18T01:12:19 IST" duration-ms="18328" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyDashboardPageContents()[pri:0, instance:com.hrm.testcases.TC_007_VerifyDashboardModule@514eedd8]" started-at="2023-09-18T01:12:19 IST" name="verifyDashboardPageContents" finished-at="2023-09-18T01:12:30 IST" duration-ms="10997" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDashboardPageContents -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_007_VerifyDashboardModule@514eedd8]" started-at="2023-09-18T01:12:30 IST" name="tearDown" finished-at="2023-09-18T01:12:33 IST" duration-ms="3173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.hrm.testcases.TC_007_VerifyDashboardModule -->
      <class name="com.hrm.testcases.TC_002_VerifyHomeLoginWithCredentials">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_002_VerifyHomeLoginWithCredentials@410954b]" started-at="2023-09-18T00:56:01 IST" name="setup" finished-at="2023-09-18T00:56:20 IST" duration-ms="18636" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="invalidPasswordAttempt()[pri:0, instance:com.hrm.testcases.TC_002_VerifyHomeLoginWithCredentials@410954b]" started-at="2023-09-18T00:56:20 IST" name="invalidPasswordAttempt" finished-at="2023-09-18T00:56:27 IST" duration-ms="7034" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidPasswordAttempt -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_002_VerifyHomeLoginWithCredentials@410954b]" started-at="2023-09-18T00:56:27 IST" name="tearDown" finished-at="2023-09-18T00:56:30 IST" duration-ms="2932" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrm.testcases.TC_002_VerifyHomeLoginWithCredentials@410954b]" started-at="2023-09-18T00:56:30 IST" name="setup" finished-at="2023-09-18T00:56:47 IST" duration-ms="16728" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validPasswordAttempt()[pri:0, instance:com.hrm.testcases.TC_002_VerifyHomeLoginWithCredentials@410954b]" started-at="2023-09-18T00:56:47 IST" name="validPasswordAttempt" finished-at="2023-09-18T00:57:03 IST" duration-ms="16010" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.hrm.testcases.TC_002_VerifyHomeLoginWithCredentials.validPasswordAttempt(TC_002_VerifyHomeLoginWithCredentials.java:83)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validPasswordAttempt -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_002_VerifyHomeLoginWithCredentials@410954b]" started-at="2023-09-18T00:57:03 IST" name="tearDown" finished-at="2023-09-18T00:57:08 IST" duration-ms="5123" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.hrm.testcases.TC_002_VerifyHomeLoginWithCredentials -->
    </test> <!-- HrmTest1 -->
    <test started-at="2023-09-18T01:12:34 IST" name="HrmTest2" finished-at="2023-09-18T01:12:57 IST" duration-ms="23370">
      <class name="com.hrm.testcases.TC_006_DataDrivenTestingFor3FailedAttempts">
        <test-method is-config="true" signature="setupBeforeTest()[pri:0, instance:com.hrm.testcases.TC_006_DataDrivenTestingFor3FailedAttempts@16afbd92]" started-at="2023-09-18T01:12:34 IST" name="setupBeforeTest" finished-at="2023-09-18T01:12:49 IST" duration-ms="14834" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupBeforeTest -->
        <test-method signature="verifyLoginWithThreeWrongAttempts(java.lang.String,java.lang.String)[pri:0, instance:com.hrm.testcases.TC_006_DataDrivenTestingFor3FailedAttempts@16afbd92]" started-at="2023-09-18T01:12:49 IST" name="verifyLoginWithThreeWrongAttempts" data-provider="multiple-user-credentials" finished-at="2023-09-18T01:12:51 IST" duration-ms="2073" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.hrm.testcases.TC_006_DataDrivenTestingFor3FailedAttempts.verifyLoginWithThreeWrongAttempts(TC_006_DataDrivenTestingFor3FailedAttempts.java:46)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithThreeWrongAttempts -->
        <test-method signature="verifyLoginWithThreeWrongAttempts(java.lang.String,java.lang.String)[pri:0, instance:com.hrm.testcases.TC_006_DataDrivenTestingFor3FailedAttempts@16afbd92]" started-at="2023-09-18T01:12:51 IST" name="verifyLoginWithThreeWrongAttempts" data-provider="multiple-user-credentials" finished-at="2023-09-18T01:12:53 IST" duration-ms="1799" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass2]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.hrm.testcases.TC_006_DataDrivenTestingFor3FailedAttempts.verifyLoginWithThreeWrongAttempts(TC_006_DataDrivenTestingFor3FailedAttempts.java:46)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithThreeWrongAttempts -->
        <test-method signature="verifyLoginWithThreeWrongAttempts(java.lang.String,java.lang.String)[pri:0, instance:com.hrm.testcases.TC_006_DataDrivenTestingFor3FailedAttempts@16afbd92]" started-at="2023-09-18T01:12:53 IST" name="verifyLoginWithThreeWrongAttempts" data-provider="multiple-user-credentials" finished-at="2023-09-18T01:12:55 IST" duration-ms="1796" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass3]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.hrm.testcases.TC_006_DataDrivenTestingFor3FailedAttempts.verifyLoginWithThreeWrongAttempts(TC_006_DataDrivenTestingFor3FailedAttempts.java:46)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithThreeWrongAttempts -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hrm.testcases.TC_006_DataDrivenTestingFor3FailedAttempts@16afbd92]" started-at="2023-09-18T01:12:55 IST" name="tearDown" finished-at="2023-09-18T01:12:57 IST" duration-ms="2835" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.hrm.testcases.TC_006_DataDrivenTestingFor3FailedAttempts -->
    </test> <!-- HrmTest2 -->
  </suite> <!-- Suite -->
</testng-results>
